# Generated by Django 3.0.6 on 2020-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlab',
            name='duration',
            field=models.TextField(),
        ),
    ]
