# Generated by Django 3.0.6 on 2020-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0002_auto_20200517_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlab',
            name='level',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
