# Generated by Django 3.0.6 on 2020-05-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0003_auto_20200517_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlab',
            name='subject',
            field=models.CharField(max_length=120),
        ),
    ]
