# Generated by Django 3.0.6 on 2020-05-28 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0005_newlab_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlab',
            name='images',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
