# Generated by Django 3.0.6 on 2020-05-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0007_auto_20200530_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newlab',
            old_name='images',
            new_name='image',
        ),
    ]
