# Generated by Django 3.0.6 on 2020-06-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Choisir un sujet pour ce cours', null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.Subject'),
        ),
    ]
