# Generated by Django 3.0.6 on 2020-06-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_cours_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscrit_Cours',
        ),
    ]
